services:
  frontend:
    image: robot-controller:frontend
    #    volumes:
    #      - type: bind
    #        source: /home/ubuntu/robot-controller.map4.jp/frontend/vue
    #        target: /vue

    volumes:
      - ./frontend/remote-robot-controller:/app # ← ローカルのfrontendをマウント
    working_dir: /app
    expose:
      - "5173"
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VIRTUAL_PORT=5173
      - VIRTUAL_HOST=robot-controller.map4.jp
      - LETSENCRYPT_HOST=robot-controller.map4.jp
      - LETSENCRYPT_EMAIL=abraham.monrroy@map4.jp

  backend:
    image: robot-controller:api
    ports:
      - "80:80"
    volumes:
      - ./backend:/app # ← ローカルのコードをマウント
    command: "uvicorn test.test_main:app --host 0.0.0.0 --port 80 --reload"
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=api.robot-controller.map4.jp
      - LETSENCRYPT_HOST=api.robot-controller.map4.jp
      - LETSENCRYPT_EMAIL=abraham.monrroy@map4.jp

networks:
  proxy:
    external: true
