version: "3.8"

services:
  backend:
    build: .
    container_name: rtwebsocket_container
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
    privileged: true